e_gamebook_chapters:
    resource: "@EGamebookBundle/Resources/config/routing/chapters.yml"
    prefix:   /chapters

e_gamebook_books:
    resource: "@EGamebookBundle/Resources/config/routing/book.yml"
    prefix:   /books

e_gamebook_profil:
    resource: "@EGamebookBundle/Resources/config/routing/profil.yml"
    prefix:   /profil

e_gamebook_homepage:
    path:     /
    defaults: { _controller: EGamebookBundle:View:intro }


