e_gamebook_chapters:
    resource: "@EGamebookBundle/Resources/config/routing/chapters.yml"
    prefix:   /chapters

e_gamebook_books:
    resource: "@EGamebookBundle/Resources/config/routing/books.yml"
    prefix:   /books

e_gamebook_profil:
    resource: "@EGamebookBundle/Resources/config/routing/profil.yml"
    prefix:   /profil

e_gamebook_homepage:
    path:     /index
    defaults: { _controller: EGamebookBundle:Chapters:index }

e_gamebook_story:
    path:     /chap/{number}
    defaults: { _controller: EGamebookBundle:View:chap }

e_gamebook_intro:
    path:     /
    defaults: { _controller: EGamebookBundle:View:intro }

e_gamebook_about:
    path:     /about
    defaults: { _controller: EGamebookBundle:View:about}


