e_gamebook_chapters:
    resource: "@EGamebookBundle/Resources/config/routing/chapters.yml"
    prefix:   /chapters

e_gamebook_books:
    resource: "@EGamebookBundle/Resources/config/routing/book.yml"
    prefix:   /books

e_gamebook_profil:
    resource: "@EGamebookBundle/Resources/config/routing/profil.yml"
    prefix:   /profil

e_gamebook_list:
    path:     /list
    defaults: { _controller: EGamebookBundle:View:listBooks }

e_gamebook_intro:
    path:     /intro/
    defaults: { _controller: EGamebookBundle:View:introBook }
    methods:  GET

e_gamebook_read:
    path:     /read/
    defaults: { _controller: EGamebookBundle:View:readBook }
    methods:  GET

e_gamebook_firsPage:
    path:     /
    defaults: { _controller: EGamebookBundle:View:firstPage }

