e_gamebook_chapters:
    resource: "@EGamebookBundle/Resources/config/routing/chapters.yml"
    prefix:   /chapters

e_gamebook_homepage:
    path:     /
    defaults: { _controller: EGamebookBundle:Default:index }

e_gamebook_story:
    path:     /chap/{id}
    defaults: { _controller: EGamebookBundle:View:chap }

e_gamebook_intro:
    path:     /intro
    defaults: { _controller: EGamebookBundle:View:intro }

e_gamebook_about:
    path:     /about
    defaults: { _controller: EGamebookBundle:View:about}
