EGamebookBundle\Entity\Chapters:
    type: entity
    table: null
    repositoryClass: EGamebookBundle\Repository\ChaptersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: integer
        content:
            type: text
        media:
            type: string
            length: 255
            nullable: true
        decision:
            type: text
        buttonText:
            type: string
            length: 255
    lifecycleCallbacks: {  }
#
#
#    manyToMany:
#        targetEntity: EGamebookBundle\Entity\Chapters
#        mappedBy: toChapters
#
#        joinTable:
#            name: chapt_relations
#            joinColumns:
#                name: chapt_id
#                        referencedColumnName: id
#            inverseJoinColumns:
#                name: chapt_relations_id
#                        referencedColumnName: id
#inversedBy: fromChapters

    manyToMany:
        parents:
            targetEntity: EGamebookBundle\Entity\Chapters
            mappedBy: childs


        childs:
            targetEntity: EGamebookBundle\Entity\Chapters
            inversedBy: parents
            joinTable:
                name: chapt_relations
                joinColumns:
                    parent_chapter:
                        referencedColumnName: id
                inverseJoinColumns:
                    child_chapter:
                        referencedColumnName: id