EGamebookBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }

    oneToMany:
        books:
            targetEntity: EGamebookBundle\Entity\Book
            mappedBy: user
            cascade: ["persist"]

